### ISSUE TITLE
sqlite3 version needs to be specified

### ISSUE THREAD

**Issue by howardemilya** [learn-co-curriculum/rails-long-running-tasks-lab#10]
the most recent version (or not specifying the version) of sqlite3 causes error: 

"An error occurred while loading ./spec/controllers/songs_controller_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

Gem::LoadError:
  Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
"
Even though it is already in gemfile and running bundle install doesn't help. 

Solution: 

changing gemfile to specify:
gem 'sqlite3', '~> 1.3.13'

then running `bundle update`

**Comment by maxwellbenton** [comment]
Hi @howardemilya,

We've recently updated all Ruby and Rails lessons using sqlite3 so that they use `gem 'sqlite3', '~> 1.3.13'` and believe this issue has been resolved.

Thank you for spotting this and providing feedback!
