### ISSUE TITLE
Essential line removed for commit 'reverted rails to 5.0.7.1'

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/rails-long-running-tasks-lab#11]
The commit `reverted rails to 5.0.7.1` removed the line `require 'rails_helper'` from `songs_controller_spec.rb` file. This causes an error `Uninitialized constant SongsController` 

Solution: Return `require 'rails_helper'` to `songs_controller_spec.rb`

**Comment by maxwellbenton** [comment]
Hi @micahshute,

Thank you for spotting this and providing feedback. I've added this line back in to `songs_controller_spec.rb` and confirmed that this issue has been resolved.

Thank you for contributing to a learn.co lesson!
